name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [v1.10, v1.11, v1.12, v1.13, canary]

    steps:
      - uses: actions/checkout@v2
      - name: Use Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@main
        with:
          deno-version: ${{ matrix.deno-version }}
      - run: time deno cache src/index.ts
      - run: time deno cache examples/*/index.ts
